[tasks.test]
run = "go test ./..."

[tasks."format:check"]
run = '[ -z "$(gofumpt -d .)" ] && echo "No formatting needed" || echo "gofumpt failed"'

[tasks.format]
run = "gofumpt -l -w ."

[tasks.generate]
run = "go generate ./..."

[tasks.lint]
run = "golangci-lint run ./..."

[tools]
gofumpt = "0.9.1"
golangci-lint = "2.12.2"
lefthook = "1.13.6"
go = "1.26.1"
